services:
  nyx-core:
    build: .
    container_name: nyx_core
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - nyx-db

  nyx-db:
    image: mongo:latest
    container_name: nyx_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - nyx_db_data:/data/db

volumes:
  nyx_db_data:
